//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kortortenet_fej
    {
        public int KortortenetFejID { get; set; }
        public Nullable<int> BetegID { get; set; }
        public Nullable<short> Deleted { get; set; }
    }
}
