//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gyogyszer
    {
        public int GyogyszerID { get; set; }
        public string Megnevezes { get; set; }
        public string Hatoanyag { get; set; }
        public Nullable<int> Mennyiseg { get; set; }
        public string Egyseg { get; set; }
        public Nullable<int> EgysegMennyiseg { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public Nullable<int> Threshold { get; set; }
    }
}
