//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idopontok
    {
        public int IdopontID { get; set; }
        public Nullable<int> BetegID { get; set; }
        public Nullable<int> OrvosID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
