//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorhaziEszkozok_Fej
    {
        public int Eszkoz_FejID { get; set; }
        public string Megnevezes { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
