//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kortortenet_tetel
    {
        public int KortortenetTetelID { get; set; }
        public Nullable<int> KortortenetFejID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Orvos { get; set; }
        public string Kezeles { get; set; }
        public Nullable<short> Deleted { get; set; }
    }
}
