//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lazlap
    {
        public int LazlapID { get; set; }
        public Nullable<int> BetegID { get; set; }
        public Nullable<int> OrvosID { get; set; }
        public Nullable<int> ApoloID { get; set; }
        public string OrvosMegjegyzes { get; set; }
        public string ApoloMegjegyzes { get; set; }
        public Nullable<System.DateTime> UtolsoFelvetelDatum { get; set; }
        public Nullable<int> Statusz { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string MegjegyzesTT { get { return "Orvos megj.: "+OrvosMegjegyzes+"\n Ápolói megj.: "+ApoloMegjegyzes; } }
    }
    
}
