//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MungoSystem : DbContext
    {
        public MungoSystem()
            : base("name=MungoDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApoloMuszak> ApoloMuszak { get; set; }
        public DbSet<Betegek> Betegek { get; set; }
        public DbSet<Gyogyszer> Gyogyszer { get; set; }
        public DbSet<Idopontok> Idopontok { get; set; }
        public DbSet<KiadottGyogyszer> KiadottGyogyszer { get; set; }
        public DbSet<KorhaziEszkoz> KorhaziEszkoz { get; set; }
        public DbSet<KorhaziEszkozok_Fej> KorhaziEszkozok_Fej { get; set; }
        public DbSet<Kortortenet_fej> Kortortenet_fej { get; set; }
        public DbSet<Kortortenet_tetel> Kortortenet_tetel { get; set; }
        public DbSet<Lazlap> Lazlap { get; set; }
        public DbSet<LookUps> LookUps { get; set; }
        public DbSet<People> People { get; set; }
    }
}
