//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTeszt01.EmailKuldoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailKuldoServiceReference.Email")]
    public interface Email {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Email/EmailKuldes", ReplyAction="http://tempuri.org/Email/EmailKuldesResponse")]
        void EmailKuldes(string fromAddress, string fromName, string toAddress, string toName, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Email/EmailKuldes", ReplyAction="http://tempuri.org/Email/EmailKuldesResponse")]
        System.Threading.Tasks.Task EmailKuldesAsync(string fromAddress, string fromName, string toAddress, string toName, string subject, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailChannel : EFTeszt01.EmailKuldoServiceReference.Email, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailClient : System.ServiceModel.ClientBase<EFTeszt01.EmailKuldoServiceReference.Email>, EFTeszt01.EmailKuldoServiceReference.Email {
        
        public EmailClient() {
        }
        
        public EmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EmailKuldes(string fromAddress, string fromName, string toAddress, string toName, string subject, string body) {
            base.Channel.EmailKuldes(fromAddress, fromName, toAddress, toName, subject, body);
        }
        
        public System.Threading.Tasks.Task EmailKuldesAsync(string fromAddress, string fromName, string toAddress, string toName, string subject, string body) {
            return base.Channel.EmailKuldesAsync(fromAddress, fromName, toAddress, toName, subject, body);
        }
    }
}
